import"./assets/styles-CT0Rx6PQ.js";import{a as c}from"./assets/vendor-C19taMLP.js";const g="Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMTU5ZDczMTAzOWRjYWNhYzc1ZjBkNmEyZDUzNzFjYSIsIm5iZiI6MTc0MzIwMzMwOC4zMTQsInN1YiI6IjY3ZTcyYmVjMGU4ZWU2NzgxNTY3YTQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.H1VcIsy5PEjzy4uHm47ss9XozIyh5LIka9hEmPAOO3k";c.defaults.headers.common.accept="application/json";c.defaults.headers.common["Content-Type"]="application/json";c.defaults.headers.common.Authorization=g;const u=()=>new Promise((e,n)=>{try{c.get("https://api.themoviedb.org/3/trending/all/week",{params:{language:"en-US"}}).then(t=>{e(t.data.results)}).catch(t=>console.error(t))}catch(t){console.error("getWeeklyTrends Error:",t)}}),_=()=>new Promise((e,n)=>{try{c.get("https://api.themoviedb.org/3/trending/all/day",{params:{language:"en-US"}}).then(t=>{e(t.data.results)}).catch(t=>console.error(t))}catch(t){console.error("getDayTrends Error:",t),n(t)}}),y=async e=>new Promise((n,t)=>{try{c.get(`https://api.themoviedb.org/3/movie/${e}/videos`,{params:{language:"en-US"}}).then(a=>{n(a.data)}).catch(a=>{console.error(a)})}catch(a){console.error("getMovieVideos Error:",a),t(err)}}),v=()=>new Promise((e,n)=>{try{c.get("https://api.themoviedb.org/3/movie/upcoming",{language:"en-US",page:1}).then(t=>{console.log("getUpcomingMovies:",t),e(t.data)}).catch(t=>console.error(t))}catch(t){console.error("getUpcomingMovies Error:",t)}}),b=async()=>{try{const e=['<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>'],n=document.querySelector("#hero__content-title"),t=document.querySelector("#hero__content-stars"),a=document.querySelector("#hero__content-info-text"),i=document.querySelector("#hero-content-button-area"),l=document.querySelector("#hero__content-background-image"),d=Math.floor(Math.random()*20);_().then(async r=>{const o=r[d],p=Math.ceil(o.vote_average/2);l.src=`https://image.tmdb.org/t/p/original/${o.backdrop_path}`,n.textContent=o.original_name||o.original_title,a.textContent=o.overview;for(let s=0;s<p;s++)e[s]='<span class="star star"></span>';t.innerHTML=e.join(""),console.log("Hero Movie:",o,o.id),y(o.id)}).catch(r=>{console.error("Error fetching daily trends:",r)})}catch(e){console.error("Error in heroRender:",e)}},M=async e=>{try{console.log("upcomingRender function called"),console.log("film:",e);const n=document.querySelector("#stand__area-upcoming"),t=document.createElement("img");t.src=`https://image.tmdb.org/t/p/original/${e.backdrop_path}`,t.alt=e.original_name||e.original_title,t.classList.add("stand__area-upcoming-image"),n.appendChild(t);const a=document.createElement("div");a.classList.add("stand__area-upcoming-info"),a.innerHTML=`
      <h2 class="stand__area-upcoming-title">${e.original_name||e.original_title}</h2>
      <table class="stand__area-upcoming-table">
          <tr>
          <th>Release date</th> <td class="date">03.03.2023</td>
          </tr>
          <tr>
            <th>Vote / Votes</th>
            <td class="vote">
              <span>7.3</span> / <span>1260</span>
            </td>
          </tr>
          <tr>
          <th>Popularity</th> <td>03.03.2023</td>
          </tr>
          <tr>
          <th>Genre</th> <td>03.03.2023</td>
          </tr>
      </table>

      <div class="stand__area-upcoming-overview">
        <h3>ABOUT</h3>
        <p>Reclusive author Loretta Sage writes about exotic places in her popular adventure novels that feature a handsome cover model named Alan. While on tour promoting her new book with Alan, Loretta gets kidnapped by an eccentric billionaire who hopes she can lead him to an ancient city's lost treasure from her latest story. Determined to prove he can be a hero in real life and not just on the pages of her books, Alan sets off to rescue her.</p>
      </div>

      <button type="button" id="film1312334523" class="btn btn-orange-black">Add to my library</button>
    `,n.appendChild(a)}catch(n){console.error("Error in upcomingRender:",n)}},C=document.querySelector("#weekly-trends-list"),T={28:"Action",12:"Adventure",16:"Animation",35:"Comedy",80:"Crime",99:"Documentary",18:"Drama",10751:"Family",14:"Fantasy",36:"History",27:"Horror",10402:"Music",9648:"Mystery",10749:"Romance",878:"Science Fiction",10770:"TV Movie",53:"Thriller",10752:"War",37:"Western"},E=e=>{const n=e.first_air_date||e.release_date,t=Math.ceil(e.vote_average/2),a=e.genre_ids.map(m=>T[m]||"Unknown").flat(1),i=document.createElement("li");i.classList.add("stand__area-item"),i.style.cursor="pointer";const l=document.createElement("img");l.src=`https://image.tmdb.org/t/p/original/${e.poster_path}`,l.alt=e.original_name||e.original_title,l.title=e.original_name||e.original_title,i.appendChild(l);const d=document.createElement("div");d.classList.add("stand__area-item-content");const r=document.createElement("h3");r.classList.add("stand__area-item-title"),r.textContent=e.original_name||e.original_title,d.appendChild(r);const o=document.createElement("div");o.classList.add("stand__area-item-content-footer");const p=document.createElement("p");p.classList.add("stand__area-item-info"),p.textContent=a.join(", ")+" | "+n.split("-")[0],o.appendChild(p);const s=document.createElement("div");s.classList.add("stand__area-item-rating");const h=['<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>'];for(let m=0;m<t;m++)h[m]='<span class="star star"></span>';return s.innerHTML=h.join(""),o.appendChild(s),d.appendChild(o),i.appendChild(d),i};u().then(e=>{console.log(e);for(let n=0;n<3;n++){const t=e[n];let a=E(t);C.appendChild(a)}});document.addEventListener("DOMContentLoaded",async()=>{try{b(),v().then(e=>{const n=Math.floor(Math.random()*e.results.length);M(e.results[n])})}catch(e){console.error("Error loading data in DOMContentLoaded event:",e)}});
//# sourceMappingURL=index.js.map
